### ISSUE TITLE
[FABRIC] Expected Crash w/ VanillaDeathChest

### ISSUE THREAD

**Issue by itsNordLord** [Lizard-Of-Oz/Inventorio#1]
### With maximum **Deep Pockets** enchantment, player inventory can exceed a double chests worth of inventory space, causing a crash when [VanillaDeathChest ](https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest-fabric) attempts to container these items.

I can crosspost this to their issue tracker instead since it is _technically_ a limitation by their mod, however compatibility with other gravestone-esque mods should be considered.

You can also consider making **Deep Pockets** toggleable in the configuration file as an end-all-be-all solution. I would instead daydream about Inventorio support for the many Backpack mods, or its own implementation. 

**Log**: 
[latest.log](https://github.com/Lizard-Of-Oz/Inventorio/files/6512261/latest.log)

**Mods**: 
![image](https://user-images.githubusercontent.com/68762570/118904586-082f7100-b8cf-11eb-81a8-91e30bd987fb.png)

**Comment by Lizard-Of-Oz** [comment]
Can confirm this bug and that it it's a limitation of their mod.
**There's a workaround tho.** If you set `container_type = "SINGLE_CHEST"` in `%root_folder%/config/vanilladeathchest.toml`, it will drop the rest of the items on the ground.

That said, pretty much no gravestone mod works correctly with this mod. I'll have to think what to do with it.

**Comment by IAmSneak** [comment]
I tested this with vanilla death chest and it seems to have just dropped the extra ones on the ground and didn't crash the game.

**Comment by Lizard-Of-Oz** [comment]
It crashes when you die with a `container_type` option being set to `SINGLE_OR_DOUBLE_CHEST` if you have more than a doublechest worth of items on you.

**Comment by Lizard-Of-Oz** [comment]
VanillaDeathChest has been deemed incompatible with Inventorio. I recommend using other gravestone mods instead.
