### ISSUE TITLE
supports trinkets API

### ISSUE THREAD

**Issue by Q2297045667** [Lizard-Of-Oz/Inventorio#100]
Trinkets cannot be used when inventorio is enabled
![图片](https://user-images.githubusercontent.com/42416195/150899160-bc04521b-5715-439a-83e3-be7905919d3c.png)
It can be used normally when inventorio is closed
If possible, I would like to omit this step
![图片](https://user-images.githubusercontent.com/42416195/150899472-2df4cf9a-0a1a-4979-aa22-830f149a8a36.png)

The above news comes from Baidu translation

**Comment by Lizard-Of-Oz** [comment]
The issue is known (and this is why "disable inventorio" button was added), but making the two mods compatible has proven to be too difficult and unstable.
As much as I'd like to, this won't happen.
