### ISSUE TITLE
Failed to replace stone axe with stone axe

### ISSUE THREAD

**Issue by janissimsons** [Lizard-Of-Oz/Inventorio#102]
Sometimes I get an error message across the entire screen (very annoying): Failed to replace stone axe with stone axe.

I have one stone axe in inventorio slot and one stone axe in regular slot (in my hand). 
Not really sure when it's triggered, but sometimes I switch between my axe and some random other tool, try to mine wood and then it throws this error.

What is causing this and how can it be avoided?
Also how to get rid of those annoying messages? If it's not a bug that's crashing the entire game, then I don't want to be spammed with errors.

**Comment by Lizard-Of-Oz** [comment]
I think it's related to some other mod, because my mod doesn't have the "Failed to replace" line.
In case it's somehow a vanilla error and you have a mod that displays exceptions on the screen, you can send the error log (`logs/latest.log`) here.

**Comment by janissimsons** [comment]
Yes, you are right, it is related to Inventory Profiles Next mod, which is supposed to be compatible with Inventorio.
Anyway, I have raised this issue on their board now.
