### ISSUE TITLE
Items Deleted When Going Through End Portal

### ISSUE THREAD

**Issue by IAmSneak** [Lizard-Of-Oz/Inventorio#11]
Fabric V1.2.1
1.16.4

When going through the exit end portal, the items in your util belt, toolbar, and deep pockets get deleted. This happens with or without the [FabricCrossDimTpFix](https://modrinth.com/mod/FabricCrossDimTPFix) mod.

**Comment by Lizard-Of-Oz** [comment]
Clarification: the commit text has a typo and that fix is applied in 1.2.2
