### ISSUE TITLE
1.18.2 would be really cool

### ISSUE THREAD

**Issue by greensad** [Lizard-Of-Oz/Inventorio#112]
While 1.18.2 tentatively works, it crashes extremely often:

Crash: https://paste.ee/p/b5y5f or https://crashy.net/zwhNEI7r69ZNXr4KZo9M

This mod still has a ton of utility in the fabric ecosystem so it would be awesome to have access to it going forward : )

**Comment by Lizard-Of-Oz** [comment]
It would be. I hope it will be. But I'm very busy right now, so, it might take time. If anyone is willing to step in, they're welcome.

**Comment by greensad** [comment]
> 

I completely understand and good luck with what's been keeping you busy. I am slowly making my way into the programming world but similarly it'll take me some time to get the point where I can lend a hand. Hopefully another Inventorio enjoyer happens across this aha

**Comment by truemogician** [comment]
I'm now working on porting this awesome mod to 1.18.2.  
Seemingly there aren't many changes in Minecraft's API that inventorio relies on, and the changes are mostly renaming.  
I've already done most of the adaption, except for `net.minecraft.tag.ServerTagManagerHolder`  
It seems that Mojang had rewritten the tag system in 1.18.2, and I cannot find a proper way to get items with a specific `net.minecraft.util.Identifier`, which is required in [`me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.testTag`](https://github.com/Lizard-Of-Oz/Inventorio/blob/e146cd7928155a0386011b7b88a91345fdc85677/common/src/main/kotlin/me/lizardofoz/inventorio/api/ToolBeltSlotTemplate.kt#L46)  
Once this problem get fixed, my porting work will soon be completed.  
So maybe someone can offer some help? I failed to find a solution on the Internet.

**Comment by Lizard-Of-Oz** [comment]
It seems like `ItemStack#streamTags` is what you're looking for and would be something like 
```java
itemStack.streamTags().anyMatch(it-> it.id() == identifier);
```

**Comment by Lizard-Of-Oz** [comment]
Thanks for taking your time to port this mod, @truemogician

**Comment by truemogician** [comment]
> It seems like `ItemStack#streamTags` is what you're looking for and would be something like
> 
> ```java
> itemStack.streamTags().anyMatch(it-> it.id() == identifier);
> ```

Great, it works! The ported version works fine, both in forge and fabric. I'll open a pull request now.

**Comment by Lizard-Of-Oz** [comment]
Glad to inform everyone that it's finally out, thanks to @truemogician!
