### ISSUE TITLE
Incompatible with Scout mod

### ISSUE THREAD

**Issue by ConqAra** [Lizard-Of-Oz/Inventorio#124]
I know there's probably not much for you to do with this, but I just wanted you to know just in case.

Mod: [https://modrinth.com/mod/scout](https://modrinth.com/mod/scout)

**Comment by Lizard-Of-Oz** [comment]
While normally a compatibility issue would just sit there forever (and deemed as a reasonable concern), I don't think people would expect Inventorio to go along with this mod in particular.
