### ISSUE TITLE
Sudden crash evidently caused by Inventorio on 1.18.1

### ISSUE THREAD

**Issue by dAKirby309** [Lizard-Of-Oz/Inventorio#133]
Version: 1.18.1
The game has been running perfectly fine with all these mods installed, until I was on another window and I see Minecraft crashed in the background. 

Crash report: 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/14/22, 10:30 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'java.util.stream.Stream net.minecraft.class_1799.method_40133()'
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.testTag(ToolBeltSlotTemplate.java:44)
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.addAllowingTag$lambda-2(ToolBeltSlotTemplate.java:26)
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.test(ToolBeltSlotTemplate.java:15)
	at me.lizardofoz.inventorio.player.inventory.PlayerInventoryExtension.findFittingToolBeltIndex(PlayerInventoryExtension.java:203)
	at me.lizardofoz.inventorio.player.inventory.PlayerInventoryExtension.findFittingToolBeltStack(PlayerInventoryExtension.java:195)
	at net.minecraft.class_329.redirect$cdb000$inventorioShowAttackIndicator(class_329.java:1542)
	at net.minecraft.class_329.method_1736(class_329.java:463)
	at net.minecraft.class_329.method_1753(class_329.java:235)
	at net.minecraft.class_757.method_3192(class_757.java:856)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.testTag(ToolBeltSlotTemplate.java:44)
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.addAllowingTag$lambda-2(ToolBeltSlotTemplate.java:26)
	at me.lizardofoz.inventorio.api.ToolBeltSlotTemplate.test(ToolBeltSlotTemplate.java:15)
	at me.lizardofoz.inventorio.player.inventory.PlayerInventoryExtension.findFittingToolBeltIndex(PlayerInventoryExtension.java:203)
	at me.lizardofoz.inventorio.player.inventory.PlayerInventoryExtension.findFittingToolBeltStack(PlayerInventoryExtension.java:195)
	at net.minecraft.class_329.redirect$cdb000$inventorioShowAttackIndicator(class_329.java:1542)
	at net.minecraft.class_329.method_1736(class_329.java:463)
	at net.minecraft.class_329.method_1753(class_329.java:235)

-- Affected level --
Details:
	All players: 1 total; [class_746['FlintonSteel'/7556, l='ClientLevel', x=1070.09, y=111.00, z=-2504.27]]
	Chunk stats: 1024, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (126,63,52), Section: (at 14,15,4 in 7,3,3; chunk contains blocks 112,-64,48 to 127,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 295926454 game time, 5983718 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, fabric-diagonal-panes/default, continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves, Better-Leaves-6.1-1.13+ for cullleaves mod.zip, z-pack-silent-minecart.zip, VanillaTweaks_r271939.zip, Nature+Revamp+Beta+v1.10.zip, Crops-3D_MC1.16.5_v1.0.0.zip, 3D Saplings, plants-by-kovaszos-uborka-e1220.zip, yuushya-foliage-addon-1-1.zip, Nic Cage paintings.zip, armoured-elytra-rp-v1-0-0.zip, xbr-clearenchantmentbooks.zip, Enchanted+Tools+v2.6.zip, Enchanted+Weapons+v2.3.zip, Redstone+Tweaks+2.2.zip, 3dited 3nchanted-books-by-kovaszos-uborka-e110.zip, FreshAnimations_v1.6.1.zip, visual-impairxfreshanimations-add-on.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 850359904 bytes (810 MiB) / 3590324224 bytes (3424 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e92
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1994
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32073.19
	Virtual memory used (MB): 24945.05
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 1430.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 3.3.1+1.18.1
		advancednbttooltip: Advanced NBT Tooltips 1.7.1-1.18.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architectury: Architectury 3.9.66
		armorhotswap: ArmorHotswap 1.7
		artifice: Artifice 0.15.6+1.18.1
		autoswitch: AutoSwitch 3.5.2
		autoswitch-api: AutoSwitch API 1.0.0
		balm-fabric: Balm 2.4.3+0
		bedspreads: Bedspreads 1.5.0-1.18
		better_wandering_trader: Better Wandering Trader 1.8.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterf3: BetterF3 1.2.2
		bottleyourxp-fabric: Bottle Your Xp (Fabric) 1.6
		brb: Better Recipe Book 1.5.6
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		carpet: Carpet Mod 1.4.57
		citresewn: CITResewn 0.9.1+1.18.1
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		clienttweaks: Client Tweaks 7.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		collective-fabric: Collective (Fabric) 4.9
		colorfularmor: Colorful Armor 1.13
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.3-1.18.1
		connectiblechains: Connectible Chains 2.0.1+1.18.1
		continuity: Continuity 1.1.0+1.18
		crowdin-translate: CrowdinTranslate 1.4+1.18
		culinaire: Culinaire 2.3.3
		cullleaves: Cull Leaves 2.3.2
		dawn: Dawn API 3.2.0
		double_hotbar: Double Hotbar 1.1.0
		dsurround: Â§6Dynamic SurroundingsÂ§r: Â§eFabric Edition 0.0.4
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18
		editsign: EditSign 2.2.7
		enchant_the_rainbow: Enchant the Rainbow 1.0.0
		enchdesc: EnchantmentDescriptions 9.0.11
		entityculling: EntityCulling-Fabric 1.5.0
		experiencebugfix: Experience Bug Fix 18
		extrapieces: Extra Pieces 2.10.1
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.3+kotlin.1.6.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabrichomes: FabricHomes 2.2.1
		fabricloader: Fabric Loader 0.13.3
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		gbfabrictools: GBfabrictools 1.3.4+1.18
		glassdoor: Glass Doors 2.1.0+1.18
		grindenchantments: Grind Enchantments 1.5.0+1.18
		indium: Indium 1.0.2-alpha3+mc1.18.1
		inventorio: Inventorio 1.7.0
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.0-pre
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		krypton: Krypton 0.1.9
		lcsl: Lightly Colored Sea Lanterns 1.1.0
		libcd: LibCapableData 3.0.3+1.16.3
		lightoverlay: Light Overlay 6.0.4
		lithium: Lithium 0.7.8
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		midnightcontrols: MidnightControls 1.0.0+1.18
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.1
		minegate-moreblocks: MineGate · MoreBlocks 1.1.8
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		modmenu: Mod Menu 3.0.1
		mostructures: Mo' Structures 1.3.1+1.18.1
		noexpensive: NoExpensive 1.18-Fabric-1.2.0
		notramplefabric: NoTrample 1.0.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_aeonbits_owner_owner: owner 1.0.12
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pandamc_concreteplus: Concrete Plus 1.9.2
		pipe: Pipe 1.6.2
		plasmo_voice: Plasmo Voice 1.2.16
		presencefootsteps: Presence Footsteps 1.4.0
		puzzleslib: Puzzles Lib 3.2.1
		quickcraft: Quickcraft 1.2.5
		rightclickharvest: Right Click Harvest 1.5.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.18.2
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		spark: spark 1.8.6
		spawnermod: Enhanced Mob Spawners 1.1.2
		spruceui: SpruceUI 3.3.2+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		strawdummy: Straw Dummy 1.6.0
		tawct: Time & Wind Custom Ticker 1.4.2+1.18
		taxfreelevels: Tax Free Levels 1.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.2.0
		trashslot: TrashSlot 11.0.2
		treeharvester-fabric: Tree Harvester (Fabric) 4.1
		villagerdeathmessages-fabric: Villager Death Messages (Fabric) 2.2
		visualworkbench: Visual Workbench 3.1.0
		walljump: Wall-Jump! 1.3.3+1.18.2
		xaerominimap: Xaero's Minimap 22.3.0
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, extrapieces:ep_assets, Fabric Mods, fabric-diagonal-panes/default (incompatible), continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves (incompatible), file/Better-Leaves-6.1-1.13+ for cullleaves mod.zip, file/z-pack-silent-minecart.zip (incompatible), file/VanillaTweaks_r271939.zip, file/Nature+Revamp+Beta+v1.10.zip, file/Crops-3D_MC1.16.5_v1.0.0.zip (incompatible), file/3D Saplings, file/plants-by-kovaszos-uborka-e1220.zip (incompatible), file/yuushya-foliage-addon-1-1.zip (incompatible), file/Nic Cage paintings.zip (incompatible), file/armoured-elytra-rp-v1-0-0.zip, file/xbr-clearenchantmentbooks.zip (incompatible), file/Enchanted+Tools+v2.6.zip, file/Enchanted+Weapons+v2.3.zip, file/Redstone+Tweaks+2.2.zip, file/3dited 3nchanted-books-by-kovaszos-uborka-e110.zip, file/FreshAnimations_v1.6.1.zip, file/visual-impairxfreshanimations-add-on.zip (incompatible)
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz

**Comment by Lizard-Of-Oz** [comment]
You've installed a version for 1.18.2 (which has had some API changes since 1.18.1).
There's a dedicated version for 1.18.0 and 1.18.1.

**Comment by dAKirby309** [comment]
Ah thanks. I originally had the version for 1.18.1, but I must've installed a newer version for 1.18.2 while I was testing some mod incompatibilities and then I forgot to remove it in place for the 1.18.1 version after I got the incompatibilities sorted out.
