### ISSUE TITLE
Jitpack.io failed to build.

### ISSUE THREAD

**Issue by jptrzy** [Lizard-Of-Oz/Inventorio#135]
I was trying to implement inventorio with my mod, but my grandle always spits out something like `Could not find com.github.Lizard-Of-Oz.Inventorio:1.19-SNAPSHOT:`.

Later I found (by entering [this](https://jitpack.io/com/github/Lizard-Of-Oz/Inventorio/1.19-3d24ad5a5c-1/build.log)) that jitpack had some problem with building your mod.

I don't think that I could do anything on my site to fix this problem.

**Comment by Lizard-Of-Oz** [comment]
JitPack pretty much doesn't work for many reasons at once.
I recommend using https://www.cursemaven.com/ instead, and will update the readme file soon.

**Comment by Lizard-Of-Oz** [comment]
In fact, my another mod, DRG Flares, uses Inventorio as a dependency, so, an example can be borrowed from there: https://github.com/Lizard-Of-Oz/DRG_Flares/blob/2917e07352ed40512e0f525f07b0f1eaf83aa61c/fabric/build.gradle#L31

**Comment by jptrzy** [comment]
Thanks.
