### ISSUE TITLE
Crash on opening config in-game

### ISSUE THREAD

**Issue by zotzot5** [Lizard-Of-Oz/Inventorio#140]
I created a world, pressed o, and the game crashed with this report:
[crash-2022-08-02_18.15.39-client.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/9247154/crash-2022-08-02_18.15.39-client.txt)

**Comment by Lizard-Of-Oz** [comment]
It seems like you haven't installed [cloth config api](https://www.curseforge.com/minecraft/mc-mods/cloth-config) which is a required dependency

**Comment by zotzot5** [comment]
turns out i downloaded the forge version instead of the fabric version, thank you!
