### ISSUE TITLE
Tinker's Construct Compatibility and QOF

### ISSUE THREAD

**Issue by slenered** [Lizard-Of-Oz/Inventorio#141]
Some tinker's tools won't place in the tools slots (Swords, Cleavers, Daggers, and Scythes)
Also, would it be possible to have an option to open to the vanilla inventory rather than the Inventorio menu?

**Comment by Lizard-Of-Oz** [comment]
1)There's an option in the settings menu that allows you to put any items into the toolbelt. Not the most elegant way, but will solve the issue.
2)The button on the top-right corner does exactly that

**Comment by slenered** [comment]
I meant when opening the inventory, i.e. press E, opens vanilla inventory.
