### ISSUE TITLE
Mending in toolbelt somehow absorb durabillity of Tools on your main hand

### ISSUE THREAD

**Issue by kanjibestgirl** [Lizard-Of-Oz/Inventorio#143]
I happened with my pickaxe suddenly, just broke when mining some coal.
when trying to replicate it it seems that tools in the toolbelt absorb all the xp they need from the main hand tool when the player is in contact with xp.

is seems that the tools in toolbelt repair way too quickly as well

**Comment by Lizard-Of-Oz** [comment]
Fixed
