### ISSUE TITLE
Error while loading mod

### ISSUE THREAD

**Issue by SecretGamerV071** [Lizard-Of-Oz/Inventorio#145]
[crash-2022-08-06_12.25.19-fml.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/9274550/crash-2022-08-06_12.25.19-fml.txt)

**Comment by Lizard-Of-Oz** [comment]
Duplicate of #139 
tl;dr - You need to download Inventorio 1.8.2 or downgrade Forge
