### ISSUE TITLE
Items duping when shift clicking in 2x2 crafting

### ISSUE THREAD

**Issue by Blug0n** [Lizard-Of-Oz/Inventorio#146]
when you shift click items in the 2x2 crafting the materials don't get used causing duplication

**Comment by Lizard-Of-Oz** [comment]
Please tell me which version you're playing:
Mod Version
Minecraft Version
Modded platform (Forge or Fabric)

I recall this bug in the past, but it was supposed to be fixed.

**Comment by Blug0n** [comment]
im playing on 1.18.2 forge, honestly i forgot 1.19 is out, and I'm glad you fixed it
