### ISSUE TITLE
[1.18.2 Forge] Not an issue just a Question

### ISSUE THREAD

**Issue by INooBTooMuch** [Lizard-Of-Oz/Inventorio#149]
There is a Dark themed UI texture available, does it exist to make resource pack makers to add compatibility easier or can we just change that?

(In case it is not for compatibility but for users I can't find where to drop the textures in)

**Comment by Lizard-Of-Oz** [comment]
In 1.19, you can just enable Dark UI as an option, but you can potentially retrofit the UI texture into a resourcepack for 1.18. Just make sure to rename it to match the original texture's name.

**Comment by INooBTooMuch** [comment]
Is it as simple as just putting the textures in .zip and the correct name into the resource pack folder, because maybe I won't be able to do it.

**Comment by Lizard-Of-Oz** [comment]
I think so. Haven't done it myself though.

**Comment by INooBTooMuch** [comment]
with or without the _dark at the end?

**Comment by Lizard-Of-Oz** [comment]
Without.

**Comment by INooBTooMuch** [comment]
So it crashed, I don't know why here's the log
log : https://gist.github.com/INooBTooMuch/8d38f3da58eadc52f086a07e6e051c6e

**Comment by Lizard-Of-Oz** [comment]
Not related to my mod.

**Comment by INooBTooMuch** [comment]
ok I will see if I can find what caused that, also the texture thing didn't work I might have to do something differently because it doesn't show up in-game
