### ISSUE TITLE
Armor loses Durability

### ISSUE THREAD

**Issue by vcgfbhtbghvghbvfghvbf** [Lizard-Of-Oz/Inventorio#154]
My Armor just lost Durability whilst Mining with a Pickaxe in the Toolbelt.

It only lost Durability when the Pickaxe picked up Xp for Mending.

 My old armor even got negative Durability and Broke because of it but i was able to repair the new Armor that had the Same problem through Mending and an XP farm.

**Comment by Lizard-Of-Oz** [comment]
> My old armor even got negative Durability and Broke because of it

Now it makes sense why this bug happens! Thanks!

**Comment by Amr7122** [comment]
Same problem here! My mending armour appears to lose durability with this mod installed. Slotting the armour into the off-hand didn't help either.
