### ISSUE TITLE
Incompatible with the trinkets mod

### ISSUE THREAD

**Issue by Aikirob** [Lizard-Of-Oz/Inventorio#160]
had to remove this one from my modlist because it interferes with a pretty crucial mod to my setup, which is trinkets.
this overrides the gui used by trinkets making it incompatible, otherwise i loved this mod, but the sword integration in the sidebar needs work.

**Comment by lazurit11** [comment]
There is a switch on the top-rignt, that opens regular inventory, where Trinkets are present. Anyway, proper Trinkets integration would be awesome.

**Comment by Lizard-Of-Oz** [comment]
1)Coming in Inventorio 2.0
2)Issue Duplication
