### ISSUE TITLE
Inventory won't open [BUG]

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Lizard-Of-Oz/Inventorio#161]
This is the entire log, which includes the mod list. I loaded the game, created a fresh world, then can't open the inventory using any key.
[Inventorio crash log](https://github.com/Lizard-Of-Oz/Inventorio/files/9331971/Inventorio.crash.log)

**Comment by Lizard-Of-Oz** [comment]
Seems like an issue in one of the 3: AirHopEnchantment, Multiconnect or Puzzleslib.
Not sure if that's even related to Inventorio, try to launch the modpack without it and see what happens. Maybe that'll generate the configs mentioned in the crash log

**Comment by DanMeadWasTaken** [comment]
So it'd appear it was in fact an issue with puzzles lib. I don't know why i even had it in there, must've been for a mod i removed previously because the pack works fine without it.
