### ISSUE TITLE
Deep Pockets enchantment unobtainable from table (& config loading the wrong option)

### ISSUE THREAD

**Issue by Mnky313** [Lizard-Of-Oz/Inventorio#163]
I know this is basically the same issue as #101 

However there's more to this issue that I figured I would add,

the config option for DeepPocketsInTreasures isn't used to set it to treasure, DeepPocketsInTrades is:

(from common\src\main\kotlin\enchantment\DeepPocketsEnchantment.kt:)

```
override fun isTreasure(): Boolean
    {
        return GlobalSettings.deepPocketsInTrades.boolValue
    }
override fun isAvailableForEnchantedBookOffer(): Boolean
    {
        return GlobalSettings.deepPocketsInTrades.boolValue
    }
```
    
I assume it should be returning GlobalSettings.deepPocketsInTreasures.boolValue

this also probably causes it to not show up in the table as disabling deepPocketsInTrades.boolValue in the config does allow it to show up in the table.

However only level 1 shows up, my guess for why this happens is the enchantment power is set too high, the minimum power is set to _level_ * 25 which is low enough for it to appear at level 1 on any leggings (assuming the table level is high enough. But when you step up to level 2 the requirement becomes 50 which is impossible to get:
![image](https://user-images.githubusercontent.com/23646586/185810090-75c04c93-5f79-4a15-b463-9f99a89ee257.png)

If I'm reading this from the wiki correctly the highest possible enchantment power would be 48.3 (and only on gold as it's enchantability is higher)

I would suggest changing the getMinPower value to something like _level_ * 3+30 which I believe would make the enchantment require high levels but not impossible to obtain.

Keep up the great work!

**Comment by Lizard-Of-Oz** [comment]
Thanks. Will release a fix in the following days. I'll probably drop the cost down even further so that it would be more common to get. After all, people want to experience this enchantment asap.
