### ISSUE TITLE
Cannot thow tridents

### ISSUE THREAD

**Issue by TheRealQuentin765** [Lizard-Of-Oz/Inventorio#165]
Holding down right click when holding a trident does not arm to throw it, like it does without the mod installed. Therefor when released nothing happens.
If I put the trident into the tool belt then i still cant throw it.
If I disable the tool belt then I still cant throw it.

Mod version:
inventorio-1.18-forge-1.7.1.jar
Forge version: 40.1.68

**Comment by Lizard-Of-Oz** [comment]
You're probably trying to throw a Trident without Loyalty and the mod has a feature that prevents Tridends without Loyalty (can be turned off in the mod settings)
