### ISSUE TITLE
Toggle Key doesnt remember what inventory

### ISSUE THREAD

**Issue by Vixeliz** [Lizard-Of-Oz/Inventorio#167]
So currently due to some usability issues and compatibility issues I have most features of the mod disabled other then the utility belt. I have binds to switch to empty slots so I dont have much need for the inventorio inventory so I like to just use the default one so most mods work. However if I toggle it off then leave inventory and come back in it goes back to the inventorio one. I would love an option to have the toggle remember which one is chosen. Or an option in the config to disable the inventorio inventory all together.

**Comment by warior456** [comment]
@Lizard-Of-Oz could we get one update to add this while we wait for 2.0?

**Comment by warior456** [comment]
in 1.18.2 preferably too

**Comment by Lizard-Of-Oz** [comment]
Will likely be only in 2.0

**Comment by warior456** [comment]
its just to store a variable

**Comment by Lizard-Of-Oz** [comment]
Right. For some reason I've thought it has to be saved across playsessions. Will do then.
