### ISSUE TITLE
[Server] Server thread/ERROR Can't find any space for item in the inventory

### ISSUE THREAD

**Issue by CrazyPenguin22** [Lizard-Of-Oz/Inventorio#171]
I think this mod is causing a crash on my server. Console spams [Server] Server thread/ERROR Can't find any space for item in the inventory, and when I log back in I am dead and my inventory is cleared. 

And this happens exactly when my inventory gets full and something else is on the floor or being crafted not being able to go in my inventory. Last thing I did before crash was shift clicking to craft wood into sticks to trade with fletcher. I filled my inventory full of sticks and while shift clicking to craft sticks when my inventory filled the game crashed. I think the game tried to put the sticks in slots your mod provides but could not and just crashed.

**Comment by Lizard-Of-Oz** [comment]
Fixed!
