### ISSUE TITLE
Curio and Cosmetic Armor Reworked menu's inaccessible 

### ISSUE THREAD

**Issue by Ezeyra** [Lizard-Of-Oz/Inventorio#173]
The Curios API mod and the Cosmetic Armor Reworked mod menu's are inaccessible when using Inventorio. You simply can't click or see the button's to open them.

**Comment by DanteTooMayCry** [comment]
Try to click on the area of ​​the red rectangle. There is a switch hidden under the book.
![2022-08-16_20 49 18](https://user-images.githubusercontent.com/108282775/189473334-0fdaefa6-f73f-40c2-b54d-e4e637b07009.png)

**Comment by Ezeyra** [comment]
> Try to click on the area of ​​the red rectangle. There is a switch hidden under the book. ![2022-08-16_20 49 18](https://user-images.githubusercontent.com/108282775/189473334-0fdaefa6-f73f-40c2-b54d-e4e637b07009.png

Yeah that works, thank you!
