### ISSUE TITLE
Request: Beeing able to disable Toolbelt (1.19.2)

### ISSUE THREAD

**Issue by entusiastaIA** [Lizard-Of-Oz/Inventorio#179]
Good morning! I love all the features this mod brings except one that, sadly, ruins all the rest. The no brainer playstyle of the Toolbelt is something I don't like. For me it is part of the fun getting stuck and having to be quick in selecting and changing tools. I totally respect all those who like it otherwise, I just wish I could disable it. I mean the area where you can leave tools and they get automatically selected.

I have checked the two config json inside one of them there is a "toolbeltmode: true" thing, but I have setted it to false and it did nothing I could notice.

**Comment by Lizard-Of-Oz** [comment]
You need to set it to `DISABLED`, not `false`.

There's also a keybind that gets enabled if you have Cloth Config API installed.

**Comment by entusiastaIA** [comment]
Oh thank youe haha, then I'd suggest that the config text were changed to
"enable" instead of true as it gets confusing, but thank you a lot!!
