### ISSUE TITLE
[BUG]Switching Tools in Mainhand with F will delete them

### ISSUE THREAD

**Issue by SugarDaddii** [Lizard-Of-Oz/Inventorio#185]
https://drive.google.com/file/d/19vB2aArOCOzZKoZ24_xCOiDSuki52b8h/view?usp=sharing

**Comment by Lizard-Of-Oz** [comment]
Seems like a mod conflict. Which mods, a modding platform and a Minecraft version do you use?

**Comment by SugarDaddii** [comment]
https://www.modpackindex.com/modpacks/compare?modpacks=52676

This is my Modpack
Version: 1.19.2
Forge: 43.1.43

**Comment by Lizard-Of-Oz** [comment]
Better Combat is known to be incompatible with Inventorio in many ways. Can't say much about the rest.
Tested a clear build with inventorio - it's definitely a compatibility issue.
Hopefully, it will be solved in 2.0, but it's not happening any time soon.
