### ISSUE TITLE
Pre-title crash in 22w43a - mixin error

### ISSUE THREAD

**Issue by BaccarWozat** [Lizard-Of-Oz/Inventorio#187]
MC: 22w43a (also tried with 22w42a)
Fabric API: 0.65.1
Inventorio: 1.8.6
Cloth Config API: 9.0.92
Fabric Language Kotlin: 1.8.5+kotlin.1.7.20

Note: I don't mind if it were not intended for 1.19.3 snapshots, and would be happy (though reluctant) to part with it for the time being, but you have it listed as working on 1.19.3 on Curseforge.

Crash log: [https://paste.ee/p/LRbXx](https://paste.ee/p/LRbXx)

`[06:40:49] [main/ERROR]: Mixin apply for mod inventorio failed inventorio.mixins.json:PlayerEntityMixin from mod inventorio -> net.minecraft.class_1657: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException
Invalid descriptor on inventorio.mixins.json:PlayerEntityMixin from mod inventorio->@Inject::inventorioCreateAddon(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;FLcom/mojang/authlib/GameProfile;Lnet/minecraft/class_7428;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)!
Expected (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;FLcom/mojang/authlib/GameProfile;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)
but found (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;FLcom/mojang/authlib/GameProfile;Lnet/minecraft/class_7428;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)]`

**Comment by Lizard-Of-Oz** [comment]
Thanks for letting me know. I shall then remove 1.19.3 from the list supported versions until it gets released and I update the mod.
