### ISSUE TITLE
Compatibility issue with Twilight Forest, Server crash when inserting item into Uncrafting Table

### ISSUE THREAD

**Issue by azza3103** [Lizard-Of-Oz/Inventorio#188]
I asked in Twilight discord, and one of the devs answered that the issue lies here somewhere
https://github.com/Lizard-Of-Oz/Inventorio/blob/1.19/common/src/main/kotlin/me/lizardofoz/inventorio/enchantment/DeepPocketsBookRecipe.kt#L46

EDIT: also added crash log
[crash-2022-11-01_19.47.39-server.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/9914032/crash-2022-11-01_19.47.39-server.txt)

**Comment by Lizard-Of-Oz** [comment]
Will investigate tomorrow.

**Comment by Lizard-Of-Oz** [comment]
It was the source of the issue indeed. The fix has been uploaded to CurseForge and it's waiting for approval.
