### ISSUE TITLE
[Incompatibility] When breaking a Gravestones grave, your current offhand item gets deleted.

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#19]
When I break a grave with items, my the item i had in offhand before i broke it gets deleted. Seems to be only the currently selected offhand slot.

**Comment by Lizard-Of-Oz** [comment]
I've made a [pull request](https://github.com/Geometrically/Gravestones/pull/31) in the mod's github page. If it won't be pulled in a near future, I'll make a mixin into that mod to fix things.
