### ISSUE TITLE
Incompatible with Loot Bag Mod (Fabric)

### ISSUE THREAD

**Issue by CheezBallzFTW** [Lizard-Of-Oz/Inventorio#194]
If I use a loot bag from the utility belt it doesn't get consumed and makes infinite items. Is there a way to force the loot bag item to only work in the right hand?

**Comment by Lizard-Of-Oz** [comment]
I'd ask the Loot Bag's mod author to use the Inventorio's API to fix this. I suspect the loot bag item is trying to delete itself, but it checks only the vanilla slots.

**Comment by L2jLiga** [comment]
Hey, fixed in commit https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/commit/b6cefcd5a6193cb39a1052824c68d0e2890ef8df

I think this issue can be closed now
