### ISSUE TITLE
[Bug] Mod overlaps with JEI Show recipes feature.

### ISSUE THREAD

**Issue by Sephoix** [Lizard-Of-Oz/Inventorio#20]
Minecraft version: 1.16.5
Forge version: 36.1.24
Inventorio version: 1.3.0
JEI version: 7.7.0.104

Issue: Inventorio overlaps with the JEI show all recipes feature in the player inventory.

Summary:
JEI uses a feature that makes a "button" that shows all recipes for any and all types of crafting you wish to see (furnace, brewing stand, crafting table, etc).
![image_2021-06-08_02-13-36](https://user-images.githubusercontent.com/85546419/121141542-b2c8ee80-c800-11eb-8d9c-8cdc62858b4e.png)
This feature extends to the player inventory placing the "button" where the arrow would be. Inventorio pushes the 2x2 crafting grid and output to the side but the show recipes feature remained in place with the button overlapping with the crafting grid of the player inventory.
![image_2021-06-08_02-14-14](https://user-images.githubusercontent.com/85546419/121142099-426e9d00-c801-11eb-9ea9-9240f5e148d7.png)

Attempted troubleshooting: I determined it was indeed JEI that had the show recipes feature as removing the mod also removed the feature. Removing inventorio with JEI installed put the inventory back to where it was and had the show recipes button back over the arrrow next to the 2x2 crafting window. I checked JEI's config to see if there was a means of disabling said feature but it does not appear there is a option.
![image_2021-06-08_02-38-56](https://user-images.githubusercontent.com/85546419/121143704-f0c71200-c802-11eb-9a1f-84c512a76700.png)

**Comment by Lizard-Of-Oz** [comment]
I've made [a request in JEI's tracker](https://github.com/mezz/JustEnoughItems/issues/2388), but if it won't be implemented in a near future, I'll implement a hacky mixin.
