### ISSUE TITLE
Very weird behavior with Requiem and Gravestones

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#22]
No idea where I should report it so imma just put it on all three githubs I guess.

Using 
Inventorio https://github.com/Lizard-Of-Oz/Inventorio
Gravestones https://github.com/Geometrically/Gravestones/issues
Requiem https://github.com/Ladysnake/Requiem

If you die while possessing a mob, weird stuff happens.
- a grave gets created, but most of the items just fall out like normal rather than go into the grave
- your currently selected hotbar slot, offhand slot gets deleted
- your currently selected toolbar slot (i was mining while it happened) gets duped

My inventory before I died
![image](https://user-images.githubusercontent.com/83337894/121188181-256db480-c869-11eb-8f9c-bca038a8a954.png)

My inventory after I died BUT before I broke the grave (all these items were on the ground)
![image](https://user-images.githubusercontent.com/83337894/121188310-47ffcd80-c869-11eb-813e-5e0829fdf274.png)

My inventory after picking up what was in the grave too
![image](https://user-images.githubusercontent.com/83337894/121188424-636ad880-c869-11eb-9994-bb2cb6dd71b5.png)

**Comment by Lizard-Of-Oz** [comment]
So far it seems to be a mod conflict between Gravestones and Requiem - even without Inventorio they have issues. But each of them separately seems to work fine with my mod (aside of #19)
That said, neither Gravestones nor Requiem like `/gamerule keepInventory true`, while my mod works with that just fine.
