### ISSUE TITLE
Issue conflict with ElytraSlot mod

### ISSUE THREAD

**Issue by wilebaldo** [Lizard-Of-Oz/Inventorio#220]
If I used this mod together with the mod ElytraSlot https://github.com/illusivesoulworks/elytraslot

the extra slot for the elytras is not more accesible with this mod actived. Realy im not sure if this is and error with your mod or with the other, but I all ready leave the problem in both place.

**Comment by Lizard-Of-Oz** [comment]
Inventorio is "semi-incompatible" with Trinkers and Curious, which is what that mod is using.
You can access those slots by pressing the button on the top-right corner.
