### ISSUE TITLE
Can't open inventory when in a server (using Minecraft Fabirc 1.19.3)

### ISSUE THREAD

**Issue by Kayxue** [Lizard-Of-Oz/Inventorio#225]
I just installed the mod and when I in a server, the inventory didn't show up after I pressed e (yeah I didn't change the key bind). But when I just in a single play world, the inventory can show up after I press e. What should I do?

**Comment by Kayxue** [comment]
And all info I know about that server are..... First, the server creator host the server with paper server. Second, the server creator didn't install this mod on server-side.

**Comment by Lizard-Of-Oz** [comment]
This mod needs to be installed on the server as well, otherwise it won't work.

**Comment by Lizard-Of-Oz** [comment]
Also, if the server is Paper, it's very unlikely that they technically can install a Fabric/Forge mod.
