### ISSUE TITLE
[Suggestion] A config option to disable automatically replacing almost broken tools

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#23]
sometimes u just wanna let them break

might also be nice for other automatic replacements
like automatically replacing an item when throwing it out with q lol

**Comment by Lizard-Of-Oz** [comment]
This isn't the part of my mod. That said, tell me which mods are you using; there is a lot of incompatibility potential with mods which DO prevent using almost broken tools.
