### ISSUE TITLE
Incompat with Trinkets?

### ISSUE THREAD

**Issue by Cape-City** [Lizard-Of-Oz/Inventorio#237]
I'm unsing 1.19.3 on fabric and have this 2 mods also installed:

- Trinkets (Fabric) trinkets-3.5.1.jar
- Cosmetic Armor [FABRIC] CosmeticArmor-1.19.3-1.5.0.jar

If i'm in normal hud mode it looks like this:
![grafik](https://github.com/Lizard-Of-Oz/Inventorio/assets/122229367/577d0341-1f4d-48a6-b7bc-6e4998f56186)

Within the Inventorio hud the trinket slots are gone:
![grafik](https://github.com/Lizard-Of-Oz/Inventorio/assets/122229367/d57fe367-ef2a-418a-8e6b-a895a17b1e2d)

Is this a desired behavior?

**Comment by Lizard-Of-Oz** [comment]
There's a button on the top-right corner (blocked by whatever book mod that is) that would take you to the vanilla inventory where you could use Trinkets. Better compatibility is sadly not on the roadmap, unless I could pursue Minecraft mods as a part-time job.

**Comment by Cape-City** [comment]
I found this switch - thats why i'm asking - all good!

**Comment by Cape-City** [comment]
Recipe Book is Pain is the book mod :D - instead of the normal MC recipe popup button. I will write him, if he can arrange the button to not stay in front of your on/off switch for the hud.
