### ISSUE TITLE
2x2 Crafting Grid Duplicates Items

### ISSUE THREAD

**Issue by CheezBallzFTW** [Lizard-Of-Oz/Inventorio#238]
Hey Is it possible to remove/disable the 2x2 crafting grid in the Inventorio inventory when the switch is green? I'm using Inventorio in a modpack I made (Forge 1.19.2), and I found a dupe glitch where shift clicking to receive the result when crafting doesn't consume any items used to craft. It only happens with the 2x2 grid on the Inventorio inventory. I was unable to find what mod causes the incompatibility. I tried removing every mod that I thought could affect the inventory, but it still allowed duplication, so removing/disabling the 2x2 grid would be a suitable fix I think. I'm going to be using this modpack for a server so I'd need to have it fixed if I'm going to use Inventorio on my server, and this mod is pretty essential to me at this point. :)

**Comment by Lizard-Of-Oz** [comment]
Will hopefully add this feature in a few days.

**Comment by CheezBallzFTW** [comment]
Thanks so much :)

**Comment by Lizard-Of-Oz** [comment]
A global setting to disable 2x2 crafting grid in Inventorio UI has been added.
