### ISSUE TITLE
Crash when trying ot  open inventory

### ISSUE THREAD

**Issue by aburone** [Lizard-Of-Oz/Inventorio#24]
Just installed the mod and the game crashed crashed when I tried to open the inventory.
I removed several mods that have some interaction with the inventory but nothing changed

https://hastebin.com/raw/botuwuyuje

**Comment by Lizard-Of-Oz** [comment]
Hard to tell from this log which exact mod causes the issues.
Can you please download this version (I've added extra logging), launch it and provide the entire log file?

[inventorio-1.16-fabric-1.4.0.zip](https://github.com/Lizard-Of-Oz/Inventorio/files/6641752/inventorio-1.16-fabric-1.4.0.zip)

**Comment by aburone** [comment]
Sure. But I'm in forge.
The file I uploaded was the complete crash report. Or do you mean you want latest.log?

**Comment by Lizard-Of-Oz** [comment]
> But I'm in forge.
Oh, okay, here's a forge version: [inventorio-1.16-forge-1.4.0.zip](https://github.com/Lizard-Of-Oz/Inventorio/files/6641792/inventorio-1.16-forge-1.4.0.zip)

After you get a crash with the modified version, send me your `latest.log`.

**Comment by aburone** [comment]
This is on an empty map

crash report
https://gist.githubusercontent.com/natanfudge/05893c807c2bd74de1173dafa33f8b10/raw/d9a7ad627180dffad4a238bf4ca4d3b4b01842f9/crash.txt

latest.log just before crash
https://hastebin.com/qaziqizotu.rb

Full latest.log
https://pastebin.pl/view/ea470024

**Comment by Lizard-Of-Oz** [comment]
It's Inventory Crafting Grid Mod causing issues. I'll investigate if I can make it compatible. Try to remove that mod and see if it won't crash anymore (you might want to install a stable version of Inventorio to avoid excessive logs)

**Comment by aburone** [comment]
Yup. Removed it an now everything works.
Thanks

**Comment by Lizard-Of-Oz** [comment]
Inventory Crafting Grid has been deemed to be completely incompatible with Inventorio.
