### ISSUE TITLE
compatibility issue with No Enchant Cap

### ISSUE THREAD

**Issue by StarkCraft** [Lizard-Of-Oz/Inventorio#240]
as stated in the title, I have an issue where the game will crash upon startup, inventorio works with my other mods normally, however when I add No Enchant Cap ( https://www.curseforge.com/minecraft/mc-mods/no-enchant-cap ) it refuses to launch, deactivating inventorio will launch the game normally and be fully functional, and vice versa. The exit code is 1, if  needed for context, if needed ill include crash files.

**Comment by Lizard-Of-Oz** [comment]
Can you include the `.minecraft/logs/latest.log` file after launching the 2 mods together?

**Comment by StarkCraft** [comment]
[latest.log](https://github.com/Lizard-Of-Oz/Inventorio/files/11555096/latest.log)
the mods are inconsistent, the two together now work fine, however they refuse to work otherwise. I apologize if this creates more unneeded work for you.

**Comment by Lizard-Of-Oz** [comment]
No signs of any errors in this file. Try to achieve a crash and open and post a file after it happens.

**Comment by Lizard-Of-Oz** [comment]
Show the error message that appears when you try to launch both and/or a log after a crash.

**Comment by StarkCraft** [comment]
please let me know if you need more information
[latest.log](https://github.com/Lizard-Of-Oz/Inventorio/files/11555190/latest.log)
ttps://github.com/Lizard-Of-Oz/Inventorio/assets/134478518/a0e80716-95ab-4910-830e-7a0ee8ff6764

**Comment by Lizard-Of-Oz** [comment]
I can't find any information about the error from the logs or by observing the code of No Enchant Cap. Sorry.

**Comment by StarkCraft** [comment]
thank you for your attempt, ill try to force a crash at some point if it will help

**Comment by StarkCraft** [comment]
so the issue is quite odd, I'm doing manual debug where I manually add each mod one at a time and launch a game and world, i have since found that the mod in fact does work with inventorio, however when I try to use both with canary ( https://www.curseforge.com/minecraft/mc-mods/canary ) or Carry on ( https://www.curseforge.com/minecraft/mc-mods/carry-on ) the issue before persists, I don't know if this is relevant however I thought I should inform you.
