### ISSUE TITLE
Compatibility with Better Combat

### ISSUE THREAD

**Issue by Abicce** [Lizard-Of-Oz/Inventorio#249]
I’m playing on Fabric 1.19.2 and it says that Inventorio is incompatible with any version of the Better Combat mod by ZsoltMolnarrr. It does, however, state that dual wielding mods will never be compatible with it. Is there any chance that this can be resolved?

**Comment by Lizard-Of-Oz** [comment]
Better Combat has fixed the compatibility issue in 1.20, but never backported it to 1.19. Migrate to 1.20+, or ask the Better Combat dev to backport the fix.

**Comment by Abicce** [comment]
> Better Combat has fixed the compatibility issue in 1.20, but never backported it to 1.19. Migrate to 1.20+, or ask the Better Combat dev to backport the fix.

I see! thank you so much

**Comment by Lizard-Of-Oz** [comment]
To be more specific, it required some changes on Inventorio's end too, which I did, backported and uploaded for all versions since 1.18.2. Now it's Better Combat's turn.

**Comment by Abicce** [comment]
> To be more specific, it required some changes on Inventorio's end too, which I did, backported and uploaded for all versions since 1.18.2. Now it's Better Combat's turn.

Alright! thank you so much for addressing this, I’ll try to raise the issue with the developer of Better Combat and hopefully, it’ll get fixed! 😁
