### ISSUE TITLE
[Suggestion] An option to let us scroll into an empty offhand slot

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#25]
Some features of some mods require you to have both hands empty, some people are more used to putting stuff in their offhand by scrolling onto the thing and swapping hands with hotkey.

~~Also about the broken tool auto swapping last time. Inventory Profiles completely ignores the toolbar slot tool, Tweakeroo replaces it but places the replacement on your selected hotbar slot rather than into the toolbar. Both work fine if the tool is on hotbar.~~

**Comment by Lizard-Of-Oz** [comment]
Will investigate comfortable options to achieve this.
Currently, you can throw an item from a slot by pressing Q (or Shift+Q) while your cursor is on top of a slot in the UI.
