### ISSUE TITLE
[Request]: config to disable auto toolbelt switching

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Lizard-Of-Oz/Inventorio#26]
I like everything this mod does *except* the automatic tool switching. 
I've never been a fan of automatic things like this, just my opinion. 

Could we get a config to disable this an instead control which tool is selected with: 
- modifier key+scroll
- modifier key+number

Basically it would work like the utility bar, but without the offhand swap functionality and with the limitation to just tools. 
Maybe you could render the toolbelt slots either on the opposite side of the hotbar from the utility belt or as a vertical mini-hotbar in the bottom left or right corner of the screen.

**Comment by Lizard-Of-Oz** [comment]
Minecraft is hardcoded for tools to work only in the main hand.
So, it would work only by making hotbar assigned to your offhand and tools to your main hand...
Which can already be achieved by enabling "Swapped Hands" and having tools in the Utility Belt.

![image](https://user-images.githubusercontent.com/701551/121790021-36218000-cc05-11eb-9f75-86e64b6366fc.png)

**Comment by Toadby** [comment]
I hope I'm not misunderstanding, but I don't think the offhand issue is at odds with this suggestion! If you think of the tool belt as an extension of the main hand hotbar, but reserved specifically for tools, it could be selected manually or used as an automatic tool selector, letting the player decide which they prefer.
Maybe it would require too much rewriting - and either way you decide what to add or not add - but how I am imagining it:  The option to disable auto-switching would turn the toolbelt into basically a new hotbar segment.
- Selecting the toolbelt via keybind or a modifier+scrolling would deselect whatever mainhand item is being held from the main hotbar, and instead select a tool from the toolbelt (like is already in the mod, but manual + persistent). 
- The selected tool could then be used / cycled through. Pressing a number 1-9 (or scrolling without the modifer?) would deselect the toolbelt / tool, and switch back to an item from the hotbar again. 

No offhand switching required, only the same switching that is already implemented (with the main hotbar item still appearing to be selected, but instead using an item appearing in a slot to the right of the  hotbar)
It could be more like a hotbar switcher, like Quark has, but with dedicated slots like are already in the mod.

Sorry for using so many words! Hope I made sense and am not missing some technical limitation. Thank you for reading and for the innovative mod :)
