### ISSUE TITLE
Instant game crash with FerriteCore in 1.4.0

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#28]
FerriteCore 2.0.4
Inventorio 1.4.0

Inventorio 1.3.0 worked fine.

[crash-2021-06-13_21.25.42-client.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/6644485/crash-2021-06-13_21.25.42-client.txt)

Edit: crashes even without FerriteCore, but on world creation/join after "Loading terrain" screen rather than on game start
[crash-2021-06-13_21.45.19-server.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/6644519/crash-2021-06-13_21.45.19-server.txt)

**Comment by Lizard-Of-Oz** [comment]
Seems like a conflict with RoughlyEnoughResources rather than FerriteCore. Will take a look.

**Comment by JumperCzech** [comment]
> Seems like a conflict with RoughlyEnoughResources rather than FerriteCore. Will take a look.

Tested it and seems like it's two different issues.
With FerriteCore and without RER I still crash on startup.
Without FerriteCore and with RER I crash on world load.
Both worked fine with 1.3.0 tho.
