### ISSUE TITLE
Incompatibility with Trinkets 

### ISSUE THREAD

**Issue by OrionFromBeyond** [Lizard-Of-Oz/Inventorio#299]
Im running a Modpack with a few mods that also use the Trinkets mod. Unfortunately Inventorio (Fabric 1.20.1) doesn't seem to be compatible with it. I feel like this is one of those mods that it really should be compatible with.

**Comment by Lizard-Of-Oz** [comment]
You can access the Trinkets menu by pressing a toggle in the top-right corner. It takes you from Inventorio menu to vanilla inventory menu, which trinkets modifies.
Other than that there's no good solution for it sadly.
Also, a duplicate.
