### ISSUE TITLE
The scroll order of the utility belt should be reversed

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#30]
This has been bugging me for the longest time and I couldnt figure out why. I thought I'd just get used to it but I kept scrolling into the wrong slot. I finally figured out why lol.
In vanilla, when you scroll down, it selects the slot on the right of the one you are currently using.
When scrolling through the offhand slot, the opposite happens. The item highlighted on the left gets chosen.
Also makes more sense in inventory, since right now scrolling down selects the item thats above your currently selected item.

Or at least it would be a nice config option.

Edit: apparently i forgot which side is right and left lmao

**Comment by Lizard-Of-Oz** [comment]
[Done!](https://github.com/Lizard-Of-Oz/Inventorio/releases/tag/v1.4.2)
