### ISSUE TITLE
[Incompatibility] Extra Alchemy's potion rings don't work if placed in utility belt or deep pockets

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#31]
https://github.com/zabi94/ExtraAlchemy/issues/110

**Comment by Lizard-Of-Oz** [comment]
`InventorioAPI` has been added and allows other mods to make items tick inside Inventorio slots. @zabi94

**Comment by zabi94** [comment]
I can't seem to pull the artifact from jitpack, weirdly. I tried both with the modCompileOnly block on your main page and the official jitpack homepage, but neither could pull successfully

**Comment by Lizard-Of-Oz** [comment]
Can confirm and went to fix it. ETA: 1 hour

**Comment by zabi94** [comment]
For the moment I'm using the cursemaven version, I'll switch to the proper repo once you're done

**Comment by Lizard-Of-Oz** [comment]
Ah, huh. It's the maven repo `https://maven.terraformersmc.com/` being currently down. Hopefully it will be up soon.

P.S. Today I've learned that cursemaven is a thing, thanks.

**Comment by Lizard-Of-Oz** [comment]
And please note that CurseForge for some reason has publicized the version that supposed to be deleted.
While API won't change across 1.17.0 and 1.17.1, it might cause confusion in terms of "where did the jar went"

**Comment by zabi94** [comment]
> P.S. Today I've learned that cursemaven is a thing, thanks.

Hahahaha you're welcome :)
Btw, the 1.17 build of Extra Alchemy implements the new API.
I assume it's the 4 extra slots that appear next to the item bar they were referring to, right? Is there any other slot I should test?
