### ISSUE TITLE
BUG [1.16.5] Items disappearing in Utility belt slot after a random amount of time.

### ISSUE THREAD

**Issue by SPARDA-REQUIEM** [Lizard-Of-Oz/Inventorio#38]
Suppose that you have a shield, crossbow, and a torch on your utility belt (or if you have a grapple gun mod, a grapple gun) [link: https://www.curseforge.com/minecraft/mc-mods/hookshot]. After a random amount of time while playing Minecraft. Items start to disappear, and I am sure that I didn't drop any of it or stored it in any chests. The items will completely disappear even though the items are in full durability. There are two things that I know of, one is that it only happened to me four times (and more as I play) and the items that disappeared are: 3 shields (unmodded), and a grapple gun (modded). Two, it likely happened during those times that I lagged, specifically server lag or TPS lags. Anyway, I will watch your career with great interest, have a nice day ahead, thank you!

P.S: There is also a time where my Diamond Pickaxe was dropped even though it is in my tool belt while mining for blocks (specifically dirt blocks using Diamond Shovel). Though, I suspect that I just pressed Q randomly during that time and it might not be a bug.

**Comment by Lizard-Of-Oz** [comment]
Could you please provide a full list of mods you're using AND inventorio settings (e.g. do you use the utility belt as your main hand)?
> Though, I suspect that I just pressed Q randomly during that time and it might not be a bug.
This might actually have a place, but it could affect the utility belt only if you're using it as your main hand.

**Comment by SPARDA-REQUIEM** [comment]
Here are the full list of mods that I am using:
![image](https://user-images.githubusercontent.com/64238265/122542735-9c6f2e00-d05d-11eb-9f9b-11d537811154.png)
![image](https://user-images.githubusercontent.com/64238265/122542817-b01a9480-d05d-11eb-862e-46b59f557470.png)
![image](https://user-images.githubusercontent.com/64238265/122542859-bdd01a00-d05d-11eb-8d44-74be3f5299d0.png)
![image](https://user-images.githubusercontent.com/64238265/122542895-c9234580-d05d-11eb-9997-74c23148639e.png)

And here are my inventorio settings:
![image](https://user-images.githubusercontent.com/64238265/122543080-f8d24d80-d05d-11eb-822d-ec4f1c1bdc1c.png)

**Comment by SPARDA-REQUIEM** [comment]
Update: As of now, 3 more items had disappeared from my utility belt, 2 shields, and 1 grapple gun. When playing the game and teleported to another location using the Waystones Mod, there is a random chance where that item disappears completely.

**Comment by SPARDA-REQUIEM** [comment]
Update: Disregard some of the things I have said (especially TPS lag) but rather, focus here:  

>  When playing the game and teleported to another location using the Waystones Mod, there is a random chance where that item disappears completely.

During hours of testing, I finally found out that the Waystones Mod is the culprit here, not the TPS lag.

**Comment by Lizard-Of-Oz** [comment]
Thank you very much. I hope to fix this issue in 2 days.

**Comment by SPARDA-REQUIEM** [comment]
Greetings! As it turns out, it was never a compatibility issue but rather, a bug from the Waystone mod itself and not Inventorio. I'm terribly sorry if I mislead you and wasted your precious time. :( I hope you have a nice day/night!

Here's the link to the said bug:
https://github.com/LordDeatHunter/FabricWaystones/issues/41

And here's the reproduction of the bug:
https://streamable.com/s6slkn
