### ISSUE TITLE
Cannot raise shield in offhand. 

### ISSUE THREAD

**Issue by TripConeHead** [Lizard-Of-Oz/Inventorio#40]
Can't be a compatibility issue, tested it with just the mod by itself and it still persists. Appears to happen in all slots. Can still raise shield in main hand, just not any off-hand slots.

**Comment by Moglibogli** [comment]
did you make the utility keybind your keybind for using the offhand?

**Comment by Lizard-Of-Oz** [comment]
Great question. To make it more clear: this mod allows you to bind "Use Offhand" to a separate keybind, which makes the regular "Use Item" keybind not apply to the Offhand. @TripConeHead are you sure the key you press should activate Offhand? Does any other item works in the Offhand?

**Comment by TripConeHead** [comment]
Keybinds were indeed my issue, your mod is very poggers, thanks for making the inventory mod mc needs. <3
