### ISSUE TITLE
Incompatibility with Charm Reforged

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [Lizard-Of-Oz/Inventorio#42]
Charm reforged https://www.curseforge.com/minecraft/mc-mods/charm-reforged (every version) seemingly causes the forge version of this mod to crash on startup. Not sure why

**Comment by KKotik** [comment]
Working fine for me.

**Comment by Lizard-Of-Oz** [comment]
Huh, apparently mods conflict due to both trying to inject into the same place in Totem of Undying's behavior.
My fix is coming soon, but you can temporary fix it by setting `TotemFromUtilityBelt` value to `false` in `config/inventorio_shared.json`
