### ISSUE TITLE
Broken Slot Compatibility for All Tools from Tetra and Tinkers Construct

### ISSUE THREAD

**Issue by SalmonSays** [Lizard-Of-Oz/Inventorio#43]
Tools from Tetra with the (I think singular shared) item ID "tetra:modular_double" and tools from Tinkers Construct with IDs like "tconstruct:pickaxe", "tconstruct:hand_axe", etc don't go into the tool slots for automatic use from inventory, which is a genuine bummer right now without a configurable whitelist built into Inventorio for manual editing/fixing. 

"tetra:modular_double" should probably be allowed in any slot given how wildly customizable they are. 

tconstruct:pickaxe, tconstruct:sledge_hammer, tconstruct:vein_hammer really should be allowed in the pickaxe slot, tconstruct:mattock in either any hatchet, shovel, or hoe slot, tconstruct:excavator in the shovel slot, tconstruct:hand_axe and tconstruct:broad_axe in the hatchet slot, tconstruct:kama, tconstruct:sword, and tconstruct:cleaver in the sword slot, and tconstruct:scythe in the hoe slot. An argument could be made for tconstruct:sledge_hammer and tconstruct:broad_axe in the sword slot as well, but really just being able to use those as default tools in the belt as intended by Inventorio would be a really welcome enhancement.

**Comment by WenXin20** [comment]
Something else I've noticed, if I try to use a tetra weapon in the main hotbar, if I attack a mob it will switch to the toolbelt instead.

**Comment by SalmonSays** [comment]
> Something else I've noticed, if I try to use a tetra weapon in the main hotbar, if I attack a mob it will switch to the toolbelt instead.

That's to be expected in terms of issue proximity. If the item ID in the hotbar isn't recognized as a tool to begin with, Inventorio will assume the same thing as if you're attacking a mob with a salmon. It makes an informed decision based on your preferred slot weapon to save you from making what it thinks is a bad choice.

**Comment by Lizard-Of-Oz** [comment]
Technically, Tetra tool is indeed "like a salmon". While Tinkers' uses built-in forge mechanisms to be considered as tools (which I've overlooked), Tetra will require individual integration which I'm about to make.

**Comment by WenXin20** [comment]
I have updated to v1.5.0, but I am still unable to equip the iron sword I made with tetra in the toolbelt.

**Comment by SalmonSays** [comment]
I noticed this too but was thinking about making a new ticket for it. It looks like the "tetra:modular_sword" item won't go into the sword or hoe slot, but goes into the pickaxe, shovel, and axe slots.

**Comment by Lizard-Of-Oz** [comment]
Tetra uses Forge's ToolType system, and depending on which heads a modular item has, Tetra mod applies corresponding tags.
Compatibility module on my end will be added in a day or two. It's an easy fix.
