### ISSUE TITLE
Compatibility with Extreme Sound Muffler and Doggy Talents?

### ISSUE THREAD

**Issue by xrosbeast** [Lizard-Of-Oz/Inventorio#44]
Really love the mod so far!

Currently, with [Extreme Sound Muffler](https://github.com/LeoBeliik/ExtremeSoundMuffler) and [Doggy Talents](https://github.com/percivalalb/DoggyTalents) installed, the gui for the tool belt overlaps like so:

![Image of Inventory](https://i.imgur.com/a4dbVDh.png)

Is it possible to make those mods compatible? If not I understand, it's a relatively minor issue.

**Comment by Lizard-Of-Oz** [comment]
Unfortunately, this request had to be rejected.
Trying to fix it "on my end" has ended up being very janky and require injects into those two mods, which can break at any time they update.
I'd recommend asking the mod authors to do something "on their end" if possible.

**Comment by xrosbeast** [comment]
I see, that's fine, I might just disable the tool belt whenever that config is potentially added.

**Comment by Lizard-Of-Oz** [comment]
Well, it's actually somewhat fixed in v1.6 - Inventorio Screen and Vanilla Player Screen and now different things.
