### ISSUE TITLE
Conflict with Diet mod

### ISSUE THREAD

**Issue by celsiusqc** [Lizard-Of-Oz/Inventorio#49]
![image](https://user-images.githubusercontent.com/63996164/123557065-cd85e780-d75c-11eb-8fbb-e7812e2e775c.png)

I think you might be adding a button where diet also adds one, which create the weird double button look

**Comment by agentwolf88** [comment]
Same problem.

**Comment by Lizard-Of-Oz** [comment]
With the amount of mod conflicts which generally boil down to "widgets and buttons get placed on top of Inventorio's stuff" it definitely needs a generalized solution. ETA: 1 week.

**Comment by Lizard-Of-Oz** [comment]
Which... Doesn't seem to be a possibility - almost every single button/widget likes to force its coordinates at arbitrary places in code.

**Comment by KKotik** [comment]
I just recommend to use Fancy Menu to place it by yourself. Or disable recipe book. That way I fixing it by myself.

**Comment by Lizard-Of-Oz** [comment]
Well, it may work for this specific thing, but then we have #44 and any generalized attempt to deal with that went nowhere.

**Comment by agentwolf88** [comment]
> I just recommend to use Fancy Menu to place it by yourself. Or disable recipe book. That way I fixing it by myself.

How can i do this? How can i chance the INGAME buttons? I use fancy menu.

**Comment by JuicyCosmos** [comment]
iirc you can simply move the button from diet mod through the config. I have the button down below the screen myself.
