### ISSUE TITLE
[Suggestion] Better Totem Activation

### ISSUE THREAD

**Issue by IAmSneak** [Lizard-Of-Oz/Inventorio#5]
It would be nice to have the totem activate if it is anywhere in the utility belt or maybe inventory. A custom slot for the totem would also work.

**Comment by Lizard-Of-Oz** [comment]
I'm still thinking what to do with Totems - I'm not sure if having them go off passively is the best idea, but being forced to hold it isn't either.

**Comment by IAmSneak** [comment]
My vote is for having it go off any time it is in your util belt because you are able to load your util belt completely full of totems right now and they will all be able to go off and save you.
