### ISSUE TITLE
[1.17] Trinkets incompatibility

### ISSUE THREAD

**Issue by GalacticRuler** [Lizard-Of-Oz/Inventorio#50]
Player logged into server and "walked 5 blocks forward", then crashed with the resulting .log file:
[latest.log](https://github.com/Lizard-Of-Oz/Inventorio/files/6725092/latest.log)
[crash-2021-06-28_05.11.48-client.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/6725093/crash-2021-06-28_05.11.48-client.txt)

My first thought, is maybe an incompatibility with Trinkets?
This crash occurs every time they log into the server. (Though the server itself seems fine)

**Comment by Lizard-Of-Oz** [comment]
Do you have a mod that removes the Crafting Book by any chance? It seems like it causes a problem

**Comment by Lizard-Of-Oz** [comment]
Regardless, I've just released a fix. But I'd like to know if that was the issue.

**Comment by GalacticRuler** [comment]
Nope, no mods that do that. Thanks for the fast fix though!

**Comment by GalacticRuler** [comment]
Well, the fix you published had no effect; opening the inventory at all causes an instant world-crash in singleplayer.
[latest.log](https://github.com/Lizard-Of-Oz/Inventorio/files/6725294/latest.log)

fresh log, from my end.
will look into trinkets incompatibility

**Comment by Lizard-Of-Oz** [comment]
Yes, this time it is trinkets incompatibility indeed. And this time it's not a one-day fix

**Comment by GalacticRuler** [comment]
Alrighty. Glad I could help narrow that down I suppose-

Good luck with the fix ^^;
