### ISSUE TITLE
Crash in 1.17. Not sure of the cause.

### ISSUE THREAD

**Issue by AlexTheDolphin0** [Lizard-Of-Oz/Inventorio#53]
The crash could be Trinkets or BackSlot. Here is the crash report attached to this issue. Please ignore the fact that I have 200 mods installed on a not fully stable version of Minecraft. Happened when I was in a Creative Mode world and then I tried opening my inventory. 
[crash-2021-07-02_23.27.36-client.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/6757839/crash-2021-07-02_23.27.36-client.txt)

**Comment by Lizard-Of-Oz** [comment]
It is very likely to be trinkets. A fix is coming in 2-3 days.
Considering this as duplicate of #50
