### ISSUE TITLE
Can't open inventory on servers

### ISSUE THREAD

**Issue by 4P5** [Lizard-Of-Oz/Inventorio#54]
This may be intentional, but I can't open my inventory on servers that don't have the mod, or are unable to install it since they aren't modded. Pressing E does nothing. If it is intentional, would it be possible to add a warning that says so in the description?

**Comment by Lizard-Of-Oz** [comment]
Yes, this mods requires to be installed on both the client and the server and things won't be stable if you'd try to connect to a server without it. I'll add a disclaimer in the description.
