### ISSUE TITLE
Duplicating items

### ISSUE THREAD

**Issue by LoudShriek** [Lizard-Of-Oz/Inventorio#55]
U can duplicate any stackable item. All u have to do is shift + right click it from hotbar to inv. 
Important, this item cannot stack while doing this process. When u have toolbelt minimized this bug wont happen.

[Gif](https://i.imgur.com/xp2uiT7.gif)

**Comment by Lizard-Of-Oz** [comment]
Confirmed. Will be fixed immediately. ETA: 1 hour.

**Comment by Lizard-Of-Oz** [comment]
Fixed. Thanks for the bugreport.
