### ISSUE TITLE
[Suggestion] Another option for "Prev/Next Utility" Skips Empty Slots

### ISSUE THREAD

**Issue by JumperCzech** [Lizard-Of-Oz/Inventorio#62]
That would make it so skips empty slots only if you already are on an empty slot. 
so for example, if you had items in slots 1 and 2 and slots 3 and 4 were empty, if you went up it would go 1>2>3>1, or backwards 2>1>4>2

**Comment by Lizard-Of-Oz** [comment]
This can already be achieved by pressing the "next empty lot" button when an empty slot is selected.

**Comment by JumperCzech** [comment]
> This can already be achieved by pressing the "next empty lot" button when an empty slot is selected.

Not really. You can use it to get to the empty slot, but not to skip empty slots to get to a non-empty slot.
Also, it's an extra button you have to use, for something extremely specific too. Especially with more mods, finding comfortable keybindings for stuff is an issue.

**Comment by Lizard-Of-Oz** [comment]
Ah, I see. I'll consider it once I have time to work on the mod. Which... might be never, not gonna lie...
