### ISSUE TITLE
Guide how to build?

### ISSUE THREAD

**Issue by RDKRACZ** [Lizard-Of-Oz/Inventorio#64]
I wanted to build it by myself but when I did `./gradlew build` I got:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fabric'.
> Could not resolve all files for configuration ':fabric:architecturyTransformerClasspath'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
   > Could not resolve net.fabricmc:fabric-loader:+.

     Required by:
         project :fabric
      > Failed to list versions for net.fabricmc:fabric-loader.
         > Unable to load Maven meta-data from https://maven.terraformersmc.com/net/fabricmc/fabric-loader/maven-metadata.xml.
            > Could not get resource 'https://maven.terraformersmc.com/net/fabricmc/fabric-loader/maven-metadata.xml'.
               > Could not GET 'https://maven.terraformersmc.com/net/fabricmc/fabric-loader/maven-metadata.xml'. Received status code 521 from server: Origin Down
```

For me (besides modmenu maven down) it looks like fabric-loader couldn't be downloaded and it's required here https://github.com/Lizard-Of-Oz/Inventorio/blob/abb8b922a5b25f5005bb6596afec9fb165455b9c/fabric/build.gradle#L24
Normally I would place the dependency into the build/loom-cache but it's not modmenu or fabric api so I don't know what to do/download. Shouldn't it be also mentioned here? https://github.com/Lizard-Of-Oz/Inventorio/blob/abb8b922a5b25f5005bb6596afec9fb165455b9c/fabric/build.gradle#L16

**Comment by Lizard-Of-Oz** [comment]
When a repo isn't responding it messes up the gradle process. Remove the terraformersmc repo from repositories until it's fixed.

**Comment by Lizard-Of-Oz** [comment]
Terraformers' maven repo is up again.
