### ISSUE TITLE
[BUG] Visual crafting bug on 1.6.1 FORGE.

### ISSUE THREAD

**Issue by KKotik** [Lizard-Of-Oz/Inventorio#66]
![image](https://user-images.githubusercontent.com/45950781/127235686-648e033d-09a3-463c-84f0-29de09bf07ec.png)
![image](https://user-images.githubusercontent.com/45950781/127235698-154a0151-3cd2-4b73-b96e-9cc70d0f66f1.png)
![image](https://user-images.githubusercontent.com/45950781/127235709-a72fe679-68ea-4664-83a1-ea9abd81e2ed.png)

**Comment by KKotik** [comment]
Also polymorth mod not working with new inventory.

**Comment by KKotik** [comment]
It is simular with #65, I am seeing it being fixed with an option of opening default inventory at first and then switching to modded one.

**Comment by Lizard-Of-Oz** [comment]
I think REI integration is more than feasible. I'll start working on the Inventorio in 2-3 days, and then it will take 3 more days for the the update do be done.
