### ISSUE TITLE
Can't open inventory at all.

### ISSUE THREAD

**Issue by RDKRACZ** [Lizard-Of-Oz/Inventorio#73]
Fabric, v1.6.2.
On one computer I can never open inventory [_Edit - I'm not so sure about this anymore, maybe I tested it two times on a server by mistake? This would make sense then._] but on my second PC, I can open it in the single-player but not when on the server. I will try to narrow it down as currently I use about 20 mods but most of them are for performance.

**Comment by Lizard-Of-Oz** [comment]
There's a chance that it creates an error log in the .minecraft/logs/latest.log, can you send it?

**Comment by RDKRACZ** [comment]
Sorry, for my late reply. I saw your comment https://www.curseforge.com/minecraft/mc-mods/inventorio?comment=90 and I think I know what's going on.
The server I was joining doesn't have this mod installed but in that case, I should just be able to open vanilla inventory right?
This log is fresh from reproducing this on my friend's PC -https://paste.ee/p/KBJYb but there is no error...

**Comment by Lizard-Of-Oz** [comment]
The mod isn't designed to join vanilla servers with (or servers without this mod)

**Comment by RDKRACZ** [comment]
Hmm, I thought since I can switch to vanilla GUI it would work. So it can't be "fixed" (sorta fallback to vanilla only GUI) in the future? If not, maybe make it print some information in the chat like "Inventorio not detected on this server"?
