### ISSUE TITLE
[Suggestion - GUI support] Curios API

### ISSUE THREAD

**Issue by Cixon** [Lizard-Of-Oz/Inventorio#78]
Hello Oz! I absolutely love your mod so far but I do not like being accustom to your '_vanilla switch_' . I understand the reason behind it (avoid modded ui issues.) but I just love Inventorio's UI and would prefer to have it standalone which is where my issue persues.

My only request is Curio support. It's a mod that supports forge and fabric and I'd hope it wouldn't be too much work.

### Something like this
![Screenshot (3)](https://user-images.githubusercontent.com/69068153/135740885-77e773e0-58dd-45e1-8497-4c0fc1e27155.png)

**Comment by Lizard-Of-Oz** [comment]
I'll add this to the Feature Wishlist, but I probably won't have time to update this mod besides porting it to the latest version of Minecraft.
If someone will pick this mod up and continue (which might be a possibility), this may or may not happen.

**Comment by Cixon** [comment]
I understand! I just found and picked up this mod recently for 1.16. I really hope this happens!

**Comment by Cixon** [comment]
Unsupported.
