### ISSUE TITLE
Mending items in toolbelt use durability from items in armor slots to repair.

### ISSUE THREAD

**Issue by Joulanh** [Lizard-Of-Oz/Inventorio#79]
Minecraft Version: 1.17.1

Mod Version: inventorio-1.17-fabric-1.6.2

Other installed mods:
   fabric-api 0.40.1+1.17
   cloth-config 5.0.38
   fabric-language-kotlin-1.6.4+kotlin.1.5.30

How to replicate:

You need at least one damaged tool with mending in the toolbelt and one damaged armor piece with mending equipped.
   /give @s minecraft:diamond_pickaxe{Damage:1500,Enchantments:[{id:meding,lvl:1}]}
   /give @s minecraft:diamond_boots{Damage:50,Enchantments:[{id:meding,lvl:1}]}

Give yourself some expirience potions and the tool wont use the new gained xp but will take it from the armor piece instead and the newly gained xp is lost.

This only works if the armor piece is already damaged and has mending on it. Armor with full durability and mending will not cause this effect.
Most of the time the armor wont break when reaching 0 durability but will go into negative values. I had it break once in about 10 tries.
The removed durability on armor pieces is the same amout as the gained durability on tools.

**Comment by johalun** [comment]
I've seen this too. Almost broke my fully spec'd out armor at my XP farm *_*  Removing tools/weapons from the tool/weapon slots as a workaround.

**Comment by Lizard-Of-Oz** [comment]
Somehow this has slept past me back in the day.
Better late than never, I guess.
