### ISSUE TITLE
Suggestion, Items Stored in Deep Pockets

### ISSUE THREAD

**Issue by Booneraniaro** [Lizard-Of-Oz/Inventorio#8]
I was thinking for the deep pockets enchantment instead of just dropping the extra items on the floor when taking the pants off, it could store the items within the pants almost like how a shulker doesn't drop the items when broken. But if the enchant gets wiped off of the pants with a grindstone it could then just drop all the items like it currently does. This could also potentially be a setting in the world config for people who prefer one way or the other? Thanks for reading!

**Comment by Lizard-Of-Oz** [comment]
At that point it would just become yet another backpack mod and we have plenty of those.
