### ISSUE TITLE
Dupe Glitch On Servers

### ISSUE THREAD

**Issue by IAmSneak** [Lizard-Of-Oz/Inventorio#9]
Fabric V1.2.0
1.16.4

I am having trouble reproducing this, so this is based on what a player in my server says. I am hosting the server on my own network and they are far away so their ping is much higher. They were able to reproduce relatively consistently.

1) Have item in utility belt (they had 6)
2) Open 2nd instance of minecraft under the same account
3) Try joining server with second instance of minecraft, then hit cancel after it kicks the first instance out and the moment before you join the server
4) The item you are holding in your utility belt is sometimes duped

**Comment by Lizard-Of-Oz** [comment]
Do you use any other mods? In particular, something that exposes the vanilla offhand slot?

**Comment by Lizard-Of-Oz** [comment]
test

**Comment by Lizard-Of-Oz** [comment]
test

**Comment by IAmSneak** [comment]
There are a lot of other mods installed. It just happened again when they regularly logged in. Here are some mods that could change something. 

Carpet
Ferritecore
Lithium
Krypton
Lazy DFU

It might be a result of the 1.2.0 update fixing the bug with updating from vanilla deleting the offhand slot because this didn't happen before the 1.2.0 update and it is happening frequently in this one.

**Comment by Lizard-Of-Oz** [comment]
Could you provide the full list of mods on the server please? I suspect it's a mod conflict. And I agree that it's probably due to that offhand fix introduced in 1.2.0

**Comment by IAmSneak** [comment]
Anvil Crushing Recipes
Ban Hammer
Better signs and frames
Blame
Blockshifter
Blockus
Bluemap
Bluemap API
Carpet Extra
Carpet TIS Addition
Chat Plus
Cloth Config
Couplings
Crowmap
Custom Item Range Combination
Data Loader
Day Dream
Dimension Update Fixer
Dim Thread
DispenserPortalFix
Drogtor-Fabric
Enderlift
Environmental Creepers
Erroring Entity Remover
Fabric API
Fabrication
Fabric Carpet
Fabric Discord Link
Fabric Language Kotlin
Fabric Language Scala
FabricCrossDimTpFix
Fabric Sit
Fabric Tailor
Fabrilous Updater
FerriteCore
Flytre_Lib
Forging Beyond
Funnel
Gentle Picking
Golden Hoppers
Lithium
Hydrogen
I Am Very Smart
Image2Map
Inventorio
InvView
ItemFlexer
KeepHeadNames
Krypton
Lapis Reserve
Lazy DFU
Lengthy Ladders
Less Annoying Piglins
LuckPerms
Mod Origins
Mod Menu
More Gems
Origins
Overpowered mending
Pehkui
Pisces
PistonControl - custom version
Polymorph
Quick Shulker
Recipe Cache
Redstone Bits
Server Restarter
Silky Spawners
Simple Drawers
Simple Server Sorter
Slime Finder
Smart Pipes
Custom Beacon Mod
Custom mod that links the overworld and end
Custom Composter Recipes Mod
Soul Capture - custom version
Spawn Lanterns
Spellbound enchants
Starlight
Stitched Snow
Telekinesis enchant
Textile Backup
TickTock
Upgraded Echests
Vanilla Death Chests
Simple Voice Chat
Walled Garden
Where Is It
Whos Pet Is This
Wires
Wither Cage Fix
Wither Totems
WorldBorderFix
Worldedit
World Specific View Distance

**Comment by Lizard-Of-Oz** [comment]
I've added a check that prevents a bugfix for #7 applying again and again, unless a player has never joined after installing a mod (and potentially has something legit in the offhand)
Please let me know if it helped.

**Comment by IAmSneak** [comment]
no dupes yet, id say its fixed
