### ISSUE TITLE
1.16.5 Fabric Server and Singleplayer client crashing with "Can't find any space for item in the inventory"

### ISSUE THREAD

**Issue by Jacobwasbeast** [Lizard-Of-Oz/Inventorio#91]
ONLY THE PLAYER CRAFTING GRID CAUSES THE ISSUE WHILE DOING THE ACTIONS

When playing 1.16.5 I crashed multiple times with only this mod installed and Fabric API  and kotlin while doing the following actions in the players crafting grid.
-Trying to switch recipe (Have a recipe already inside the crafting then select another recipe from recipe book)
-Add another item to the crafting (Have the same recipe already in then press on it in the recipe book)

"[Server thread/ERROR]: Can't find any space for item in the inventory"
This is the message the fills up the log after these actions then the server and client freezes and crashes.

**Comment by Lizard-Of-Oz** [comment]
Can confirm this bug, but only for 1.16 (both Fabric and Forge).
I hope to fix the issue in around a week, but I have a severe lack of time.
