### ISSUE TITLE
[Fabric 1.18.1] Incompatibillity with Inventory Profiles Next

### ISSUE THREAD

**Issue by Quizer9O8** [Lizard-Of-Oz/Inventorio#93]
All the buttons are displaced and overlapping each other inside of the Inventorio Inventory:
![image](https://user-images.githubusercontent.com/19509275/147349396-ece514e7-9424-4a74-bad1-a88566a35e80.png)

**Comment by AmyRose1288** [comment]
this has fixed in a recent inventory profile next update

**Comment by Lizard-Of-Oz** [comment]
Thanks for letting me know.
